name: Push Workflow

on:
  push:
    branches:
      - main

jobs:

  #Runs pnpm lint and pnpm check
  lint-check-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install npm dependencies
      run: |
        npm install -g pnpm
        pnpm install

    - run: pnpm lint
    - run: pnpm check
    
    - name: Run Tests
      run: |
        pnpm test
  
  #Runs `pnpm build_npm`
  push-npm:
    runs-on: ubuntu-22.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - run: npm install -g pnpm

    - uses: actions/checkout@v4

    - name: Install npm dependencies and build
      run: |
        pnpm install
        pnpm build_npm

    - name: Increment package version and push
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        git config --global user.name 'gmetridev'
        git config --global user.email 'techbots+build-gmetrixr@gmetri.com'

        export N=`node -p require\(\'./package.json\'\).name` && echo $N
        pnpm version patch --message "v%s: $N [CI SKIP]"

        npm set registry https://registry.npmjs.org/
        npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

        npm publish
        
        git push origin
        git push --tags origin
